export const basePath = "/panel.html"
export const newRecipePath = basePath + "/new"
export const showRecipePath = basePath + "/show/:recipeId/"
export const showRecipeBasicPath = basePath + "/show/"
export const newAttrPath = basePath + "/show/newattr"