export const basePath = "/panel.html"
export const newRecipePath = basePath + "/new"
export const showRecipePath = basePath + "/recipes/:recipeId/"
export const showRecipeBasicPath = basePath + "/recipes/"
export const newAttrPath = basePath + "/show/newattr"